### ISSUE TITLE
question: Job steps are executed by different workers!

### ISSUE THREAD

**Issue by RaiaN** [aws-deadline/deadline-cloud-samples#82]
### Describe the bug

Trying to use multiple steps within a single Deadline Cloud job. I use the following template:
```
steps:
- name: Run Diagnostics
  script:
    actions:
      onRun:
        command: python
        args: ['{{Param.DiagnosticsScript}}']
- name: Download Data
  dependencies:
  - dependsOn: "Run Diagnostics"
  script:
    actions:
      onRun:
        command: python
        args: ['{{Param.DownloadScript}}']
- name: Launch 3ds max batch render
  dependencies:
    - dependsOn: "Download Data"
  script:
    actions:
      onRun:
        command: python
        args: ['{{Param.LauncherFile}}', '{{Param.RenderScript}}']
        cancelation:
          mode: NOTIFY_THEN_TERMINATE
          notifyPeriodInSeconds: 2
```

End result (one of the steps failed cause guess what, different workers are picking up the steps from the same task!!!
![Image](https://github.com/user-attachments/assets/4bbc646c-94d2-4941-af23-c7060a457f0a)

### Expected Behaviour

Given the following job template (bundle) I expect that the same worker will execute all steps? Is it too much to ask?
![Image](https://github.com/user-attachments/assets/429c4e65-1c5c-4efe-b9ce-e2cf418d7b52)

### Current Behaviour

Different workers pick up different steps and the result is CHAOS
![Image](https://github.com/user-attachments/assets/46691a89-6a09-4b71-87c0-e21952e96c45)

### Reproduction Steps

Use the following template:
```
steps:
- name: Run Diagnostics
  script:
    actions:
      onRun:
        command: python
        args: ['{{Param.DiagnosticsScript}}']
- name: Download Data
  dependencies:
  - dependsOn: "Run Diagnostics"
  script:
    actions:
      onRun:
        command: python
        args: ['{{Param.DownloadScript}}']
- name: Launch 3ds max batch render
  dependencies:
    - dependsOn: "Download Data"
  script:
    actions:
      onRun:
        command: python
        args: ['{{Param.LauncherFile}}', '{{Param.RenderScript}}']
        cancelation:
          mode: NOTIFY_THEN_TERMINATE
          notifyPeriodInSeconds: 2
```

### Environment

Deadline Cloud, Windows render node
